export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Stats } from './Stats'
export { default as Testimonials } from './Testimonials'
export { default as CourseCards } from './CourseCards'
export { default as LeadForm } from './LeadForm'
